//
// Created by deamon on 11.09.17.
//

#ifndef WEBWOWVIEWERCPP_PORTALCULLINGALGO_H
#define WEBWOWVIEWERCPP_PORTALCULLINGALGO_H


#include "../objects/wmoObject.h"


#endif //WEBWOWVIEWERCPP_PORTALCULLINGALGO_H
